# Generated by Django 2.1.8 on 2019-08-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imageurls', models.CharField(db_column='imageUrls', max_length=1000)),
                ('publishtime', models.CharField(db_column='publishTime', max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'show_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='UserName', max_length=255)),
                ('phone', models.CharField(db_column='Phone', max_length=255)),
                ('sex', models.IntegerField()),
                ('authortriy', models.IntegerField(db_column='Authortriy')),
                ('idcard', models.CharField(db_column='idCard', max_length=255)),
                ('createtime', models.CharField(db_column='createTime', max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
